### ISSUE TITLE
После 3-го РК

### ISSUE THREAD

**Issue by NellinLin** [frontend-park-mail-ru/2020_2_ExtraSafe#15]
- [x] При пустой авторизации ничего не происходит
![image](https://user-images.githubusercontent.com/32364427/100837769-4997a580-3482-11eb-8db6-f3b56540afb2.png)
- [x] При авторизации 500 если что-то не так введено (скорей всего емейл, потому что при пароле он говорит, что не так введён пароль или емейл), хотелось бы сообщение об ошибке
- [x] При неуспешном добавлении пользователя хотелось бы видеть уведомление об этом
![image](https://user-images.githubusercontent.com/32364427/100838687-f32b6680-3483-11eb-8fb8-fa4e2f0fb827.png)
- [x] Комментарий на textarea
![image](https://user-images.githubusercontent.com/32364427/100838209-1a356880-3483-11eb-9f43-a42bec2e7709.png)

**Comment by SmailD35** [comment]
Все поправили)
